import { createDataWriter } from './src/DataWriter'
import { createDataReader } from './src/DataReader'
import {
  createViewCursor,
  sliceViewCursor,
  scrollViewCursor,
  moveViewCursor,

  writeProp,
  writePropIfChanged,
  writeFloat64,
  writeFloat32,
  writeUint64,
  writeInt64,
  writeUint32,
  writeInt32,
  writeUint16,
  writeInt16,
  writeUint8,
  writeInt8,

  spaceFloat64,
  spaceUint64,
  spaceInt64,
  spaceUint32,
  spaceInt32,
  spaceUint16,
  spaceInt16,
  spaceUint8,
  spaceInt8,

  readProp,
  readFloat64,
  readFloat32,
  readUint64,
  readInt64,
  readUint32,
  readInt32,
  readUint16,
  readInt16,
  readUint8,
  readInt8,
} from './src/ViewCursor'

export default {
  createDataWriter,
  createDataReader,

  createViewCursor,
  sliceViewCursor,
  scrollViewCursor,
  moveViewCursor,

  writeProp,
  writePropIfChanged,
  writeFloat64,
  writeFloat32,
  writeUint64,
  writeInt64,
  writeUint32,
  writeInt32,
  writeUint16,
  writeInt16,
  writeUint8,
  writeInt8,

  spaceFloat64,
  spaceUint64,
  spaceInt64,
  spaceUint32,
  spaceInt32,
  spaceUint16,
  spaceInt16,
  spaceUint8,
  spaceInt8,

  readProp,
  readFloat64,
  readFloat32,
  readUint64,
  readInt64,
  readUint32,
  readInt32,
  readUint16,
  readInt16,
  readUint8,
  readInt8,
}