import {
  createWorld,
  resetWorld,
  deleteWorld,
  getWorldComponents,
  getAllEntities,
  enableManualEntityRecycling,
} from "./world/World.js";
import {
  addEntity,
  removeEntity,
  setDefaultSize,
  setRemovedRecycleThreshold,
  getEntityComponents,
  entityExists,
  flushRemovedEntities,
  resetGlobals,
  getDefaultSize,
} from "./entity/Entity.js";
import {
  registerComponent,
  registerComponents,
  hasComponent,
  addComponent,
  removeComponent,
} from "./component/Component.js";
import {
  defineQuery,
  enterQuery,
  exitQuery,
  Changed,
  Not,
  commitRemovals,
  resetChangedQuery,
  removeQuery,
} from "./query/Query.js";

export {
  setDefaultSize,
  setRemovedRecycleThreshold,
  createWorld,
  resetWorld,
  deleteWorld,
  addEntity,
  removeEntity,
  entityExists,
  getWorldComponents,
  enableManualEntityRecycling,
  flushRemovedEntities,
  getAllEntities,
  registerComponent,
  registerComponents,
  addComponent,
  removeComponent,
  hasComponent,
  getEntityComponents,
  defineQuery,
  Changed,
  Not,
  enterQuery,
  exitQuery,
  commitRemovals,
  resetChangedQuery,
  removeQuery,
  resetGlobals,
  getDefaultSize,
};
