export const injectorUnroller = (componentManagers, update) => {
  // populate component flyweight objects and pass into an update call
  if(componentManagers.length == 1) return eid => {
      update(componentManagers[0].get(eid))
      componentManagers[0].set(eid)
  }
  else if(componentManagers.length == 2) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
      )
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
  }
  else if(componentManagers.length == 3) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
  }
  else if(componentManagers.length == 4) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
  }
  else if(componentManagers.length == 5) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
        componentManagers[4].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
      componentManagers[4].set(eid)
  }
  else if(componentManagers.length == 6) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
        componentManagers[4].get(eid),
        componentManagers[5].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
      componentManagers[4].set(eid)
      componentManagers[5].set(eid)
  }
  else if(componentManagers.length == 7) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
        componentManagers[4].get(eid),
        componentManagers[5].get(eid),
        componentManagers[6].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
      componentManagers[4].set(eid)
      componentManagers[5].set(eid)
      componentManagers[6].set(eid)
  }
  else if(componentManagers.length == 8) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
        componentManagers[4].get(eid),
        componentManagers[5].get(eid),
        componentManagers[6].get(eid),
        componentManagers[7].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
      componentManagers[4].set(eid)
      componentManagers[5].set(eid)
      componentManagers[6].set(eid)
      componentManagers[7].set(eid)
  }
  else if(componentManagers.length == 9) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
        componentManagers[4].get(eid),
        componentManagers[5].get(eid),
        componentManagers[6].get(eid),
        componentManagers[7].get(eid),
        componentManagers[8].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
      componentManagers[4].set(eid)
      componentManagers[5].set(eid)
      componentManagers[6].set(eid)
      componentManagers[7].set(eid)
      componentManagers[8].set(eid)
  }
  else if(componentManagers.length == 10) return eid => {
      update(
        componentManagers[0].get(eid),
        componentManagers[1].get(eid),
        componentManagers[2].get(eid),
        componentManagers[3].get(eid),
        componentManagers[4].get(eid),
        componentManagers[5].get(eid),
        componentManagers[6].get(eid),
        componentManagers[7].get(eid),
        componentManagers[8].get(eid),
        componentManagers[9].get(eid),
      ) 
      componentManagers[0].set(eid)
      componentManagers[1].set(eid)
      componentManagers[2].set(eid)
      componentManagers[3].set(eid)
      componentManagers[4].set(eid)
      componentManagers[5].set(eid)
      componentManagers[6].set(eid)
      componentManagers[7].set(eid)
      componentManagers[8].set(eid)
      componentManagers[9].set(eid)
  }
}